### ISSUE TITLE
Version upgrade : 3.2.5 -> 3.2.8 ?

### ISSUE THREAD

**Issue by LucTech** [ipeos-and-co/docker-spip#1]
Hi,
I'm new with docker.
I'm "playing" with spip's images.
I have installed successfully 3.2.5 (and it works, I can create articles !).

Now, I'm trying an upgrade to 3.2.8. But I failed.

Is it enough to change image version number in docker-compose file and "up" it ?
"up" and image pull seem ok.
I have used "3.2" number. Is it ok ?

Docker file seems ok with 3.2.8.

Is upgrade managed in those images ?
Do you have an idea ?

At least, thanks a lot for your job. 
Vive spip !

Luc

**Comment by psychoz971** [comment]
Hi Luc,

To start the upgrade you have to re-create the docker.
`docker stop / docker rm`

Before, make sure you use named volumes to keep sap your IMG, config, squelettes and plugins folders

**Comment by LucTech** [comment]
Thanks for stop/rm suggestion. But it does not permit upgrade (in my local environnement).

I've done another tests. Building another image from yours.
I can upgrade from admin interface (message "bdd have to be upgraded") when 
in "docker-entrypoint" script, I suppress 2 "if conditions" : 
- if ! [ -e index.php -a -e ecrire/inc_version.php ]; then
- if [ ! -e config/connect.php ]; then
It's a way to force source copy and  install, in fact...

Maybe is there a way with spip-cli : spip core:mettreajour, spip core:maj:bdd, spip plugins:maj:bdd ?

Or is it no use ? Automatic upgrade with docker is ok with your implementation ?
