### ISSUE TITLE
zip absent dans de la config php

### ISSUE THREAD

**Issue by zzzazzz** [ipeos-and-co/docker-spip#7]
Bonjour,

En ayant utilisé le docker file de la 4.2, on se retrouve avec une installation SPIP sans extension zip (du moins dans le phpinfo).
Ce qui nous empêche de faire des majs ou install de plugin en utilisant le système interne à SPIP. (du moins c'est ce qu'on pense)

Est-ce normal ? Doit-on changer cette ligne et relancer la procédure ?
https://github.com/ipeos-and-co/docker-spip/blob/a8bf38ed7e01dd77fc954b173b1289e94d113363/4.2/Dockerfile#L18C20-L18C20
Ou peut-on faire quelque chose à posteriori ?

**Comment by psychoz971** [comment]
Bonjour,
Merci d'avoir fait remonter l'erreur. Je propose une mise à jour du packet 4.2 pour le fix du zip

**Comment by psychoz971** [comment]
Il semble que le problème viennent de debian 12 (image de base de la nouvelle version de php8.1-apache).
En utilisant la version bullseye tout est rentré dans l'ordre. La nouvelle version est disponible sur docker hub
