### ISSUE TITLE
Installer des plugins avec spip-cli

### ISSUE THREAD

**Issue by nicos68** [ipeos-and-co/docker-spip#8]
Merci beaucoup pour votre image docker fort utile.

Je souhaite utiliser spip-cli pour installer des plugins. Si je m'attache au contneur avec bash et que j'exécute `spip plugins:svp:depoter https://plugins.spip.net/depots/principal.xml `, je vois bien le dépôt dans l'administration du site et je peux installer des plugins par l'interface. Néanmoins
 * Si je lance la commande `spip plugins:svp:telecharger <plugin>` j'obtiens le message suivant dans l'interface (exemple avec le plugin [nospam](https://plugins.spip.net/nospam.html)): 
```
Télécharger des plugins
=======================

 ! 20 plugins actifs
 Liste des plugins à activer :
 * nospam

 Les plugins listés au-dessus seront activés. Confirmez-vous ? (yes/no) [no]:
 > yes

 // Plugin en cours d'installation : nospam

 // Pour l'installation du plugin nospam les actions suivantes sont prévues :

 //     Télécharger et activer le plugin « NoSPAM » (version : 2.4.6)

 // NoSPAM action réalisée : geton

 ! Aucune modification des plugins actifs
```
et dans l'interface j'ai le message suivant :
![image](https://github.com/ipeos-and-co/docker-spip/assets/1062625/df59ebe2-ff39-4dac-b8d3-28b329856783)
J'obtiens le même résultat avec les plugins [yaml](https://plugins.spip.net/yaml.html), [bootstrap4](https://plugins.spip.net/bootstrap4.html?compatible_spip=4.2) ou [scssphp](https://plugins.spip.net/scssphp.html?compatible_spip=4.2). Or en passant par l'interface j'arrive à installer tous ces plugins avec succès.
 * Si j'essaye de compiler le Dockerfile ci-dessous, j'obtiens l'erreur ```0.726 In Spip.php line 189:
0.726
0.726   SPIP has not been found in /var/www/html```
```Dockerfile
FROM ipeos/spip

RUN spip plugins:svp:depoter https://plugins.spip.net/depots/principal.xml
```

----
EDIT : à propos de ce dernier point, je viens d'y penser : j'imagine que ce n'est pas possible de faire cela à la phase de build car cela suppose une interaction avec la bdd ? Mais ça ne change rien au fait qu'il est utile et important de pouvoir utiliser spip cli pour installer des plugins.

**Comment by psychoz971** [comment]
Bonjour,

Je te conseille de réécrire le entrypoint en le surchargeant avec les actions que tu souhaites réaliser.
Pour ce qui est du fonctionnement du spip-cli, je te renvoie à la documentation du projet.

Bonne journée
